POSITION_STATS = {
    "F": [
        "goals_per90",
        "expected_goals_per90",
        "assists_per90",
        "expected_assists_per90",
        "goals_assists_sum_per90",
        "total_shots_per90",
        "shots_on_target_per90",
        "successful_dribbles_per90",
        "successful_dribbles_percentage",
        "key_passes_per90",
        "big_chances_created_per90",
    ],

    "M": [
        "goals_per90",
        "expected_goals_per90",
        "assists_per90",
        "expected_assists_per90",
        "goals_assists_sum_per90",
        "accurate_passes_per90",
        "accurate_passes_percentage",
        "accurate_long_balls_per90",
        "accurate_long_balls_percentage",
        "key_passes_per90",
        "big_chances_created_per90",
        "successful_dribbles_per90",
        "successful_dribbles_percentage",
        "tackles_per90",
        "interceptions_per90",
    ],

    "D": [
        "tackles_per90",
        "interceptions_per90",
        "clearances_per90",
        "accurate_passes_per90",
        "accurate_passes_percentage",
        "accurate_long_balls_per90",
        "accurate_long_balls_percentage",
        "successful_dribbles_per90",
        "successful_dribbles_percentage",
        "goals_per90",
        "expected_goals_per90",
        "assists_per90",
        "expected_assists_per90",
        "key_passes_per90",
    ],

    "G": [
        "saves_per90",
        "goals_prevented",
        "accurate_passes_per90",
        "accurate_passes_percentage",
        "accurate_long_balls_per90",
        "accurate_long_balls_percentage",
        "possession_lost_per90",
        "rating",
    ],
}