DROP TABLE IF EXISTS player_season_stats CASCADE;

CREATE TABLE player_season_stats (
    player_id                       INTEGER REFERENCES players(player_id),
    team_id                         INTEGER REFERENCES teams(team_id),
    league                          TEXT NOT NULL,
    season                          TEXT NOT NULL,
    position                        TEXT,
    age                             INTEGER,
    minutes_played                  INTEGER,
    appearances                     INTEGER,
    multi_team                      BOOLEAN,
    meets_minutes_threshold         BOOLEAN,
    goals                           INTEGER,
    assists                         INTEGER,
    expected_goals                  DOUBLE PRECISION,
    expected_assists                DOUBLE PRECISION,
    goals_assists_sum               INTEGER,
    penalty_goals                   INTEGER,
    free_kick_goal                  INTEGER,
    total_shots                     INTEGER,
    shots_on_target                 INTEGER,
    big_chances_created             INTEGER,
    big_chances_missed              INTEGER,
    accurate_passes                 INTEGER,
    key_passes                      INTEGER,
    accurate_long_balls             INTEGER,
    successful_dribbles             INTEGER,
    tackles                         INTEGER,
    interceptions                   INTEGER,
    clearances                      INTEGER,
    possession_lost                 INTEGER,
    yellow_cards                    INTEGER,
    red_cards                       INTEGER,
    saves                           INTEGER,
    goals_per90                     DOUBLE PRECISION,
    assists_per90                   DOUBLE PRECISION,
    expected_goals_per90            DOUBLE PRECISION,
    expected_assists_per90          DOUBLE PRECISION,
    goals_assists_sum_per90         DOUBLE PRECISION,
    penalty_goals_per90             DOUBLE PRECISION,
    free_kick_goal_per90            DOUBLE PRECISION,
    total_shots_per90               DOUBLE PRECISION,
    shots_on_target_per90           DOUBLE PRECISION,
    big_chances_created_per90       DOUBLE PRECISION,
    big_chances_missed_per90        DOUBLE PRECISION,
    accurate_passes_per90           DOUBLE PRECISION,
    key_passes_per90                DOUBLE PRECISION,
    accurate_long_balls_per90       DOUBLE PRECISION,
    successful_dribbles_per90       DOUBLE PRECISION,
    tackles_per90                   DOUBLE PRECISION,
    interceptions_per90             DOUBLE PRECISION,
    clearances_per90                DOUBLE PRECISION,
    possession_lost_per90           DOUBLE PRECISION,
    yellow_cards_per90              DOUBLE PRECISION,
    red_cards_per90                 DOUBLE PRECISION,
    saves_per90                     DOUBLE PRECISION,
    rating                          DOUBLE PRECISION,
    accurate_passes_percentage      DOUBLE PRECISION,
    accurate_long_balls_percentage  DOUBLE PRECISION,
    successful_dribbles_percentage  DOUBLE PRECISION,
    scoring_frequency               DOUBLE PRECISION,
    goals_prevented                 DOUBLE PRECISION,
    scraped_at                      TIMESTAMP WITH TIME ZONE,
    UNIQUE (player_id, league, season)
);